apiVersion: apps/v1
kind: Service
metadata:
  name: myapp-deployment
spec:
  type: ClusterIP
  ports:
   - targetPort: 80
     port: 80
  selector:
   app: nginx ### labels form deployement or from pod
   env: production

## if noticed we are not passing nodeport as we are assigning ip to the entire cluster