apiVersion: apps/v1
kind: Service
metadata:
  name: myapp-deployment
  labels:
    app: nginx
    env: production
spec:
  type: LoadBalancer
  ports:
   - targetPort: 80
     port: 80
     nodePort: 30008 ## mapping port of the node to pod
  selector:
   app: nginx ### labels form deployement or from pod
   env: production

## nodeport is required in load balancer, it is not used in cluster IP